# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: False
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: False

zone_system: 1

taz_skims: skims_MRDH2_new.omx

skim_time_periods:
    time_window: 1440
    period_minutes: 60
    periods: [0, 7, 9, 16, 18, 24] # 3=3:00-3:59, 5=5:00-5:59, 9=9:00-9:59, 14=2:00-2:59, 18=6:00-6:59
    labels: ['RD', 'OS', 'RD', 'AS', 'RD']
