
SPEC: atwork_subtour_destination.csv
SAMPLE_SPEC:  atwork_subtour_destination_sample.csv
COEFFICIENTS: atwork_subtour_destination_coefficients.csv

SAMPLE_SIZE: 30

SIZE_TERM_SELECTOR: atwork

SEGMENTS:
  - atwork

ORIG_ZONE_ID: workplace_zone_id

SIMULATE_CHOOSER_COLUMNS:
  - person_id
  - income_segment
  - workplace_zone_id
  - tour_type               # add by Han due to requirement in tour mode choice
  - number_of_participants  # add by Han due to requirement in tour mode choice
  - tour_category           # add by Han due to requirement in tour mode choice, tour_destination.py also updated


LOGSUM_SETTINGS: tour_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: workplace_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 14
OUT_PERIOD: 14
