USE_CRN: 1
SIGMA_FOR_CRN: 0.265
USE_GPU: 1
#PATH_DLL_ACC_EGR_MODEL: "C:\\Users\\zhouh\\surfdrive\\work\\ActivityBasedModeling\\ABM\\bin\\Release_CPU\\dll_access_egress_cpu.dll"
PATH_DLL_ACC_EGR_MODEL: "L:/UserData/Han/activitysimtno2021/dll_access_egress_cpu.dll"

EXPORT_TRIPS_2_HDF: 0  # if 1, the program will export the trips to HDF file and should enable trip_access_egress_mode_choice_load function and disable trip_access_egress_mode_choice
EXPORT_TRIPS_NAME: "before_call_500.h5"
SEED_FOR_MU: 42     # not used if USE_CRN is 1
SEED_OFFSET_ETA: 0  # not used if USE_CRN is 1
export_utility: 0
enable_maas: 1
USE_HUBS: 1
use_FEATHERS_trips: 0
DELFT_AREA: 0
parking_factor: 1.0
SIGMA_PERCENT: 0.1  # not used if USE_CRN is 1

# deprecated: MAAS_CAR_COST_PERCENT: 0.5
# deprecated: MAAS_CP_COST_PERCENT: 0.5
# deprecated: MAAS_BIKE_COST_PERCENT: 0.5
# deprecated: MAAS_EBIKE_COST_PERCENT: 0.5
# deprecated: MAAS_DRT_COST_PERCENT: 0.5
# deprecated: MAAS_PT_COST_PERCENT: 0.5
# deprecated: ASC_PT_INC_PERCENT: -0.2

SHR_CAR_COST_PCT: 1.0
SHR_CAR_TT_PCT: 1.0
# elasticity check
PT_TT_10_PCT_HIGHER: 1.0
PT_COST_10_PCT_HIGHER: 1.0
CAR_TT_10_PCT_HIGHER: 1.0
CAR_COST_10_PCT_HIGHER: 1.0
BIKE_TT_PCT: 1.0
EBIKE_TT_PCT: 1.0
DRT_TT_PCT: 1.0
DRT_COST_PCT: 1.0
DRT_TT_BETA_MORE_SENSITIVE: 1.0
DRT_COST_BETA_MORE_SENSITIVE: 1.0
PT_TT_BETA_MORE_SENSITIVE: 50
PT_COST_BETA_MORE_SENSITIVE: 45
CAR_TT_BETA_MORE_SENSITIVE: 25
CAR_COST_BETA_MORE_SENSITIVE: 40

# tunning for mode choice:
WALK_PENALTY: 9.7
BIKE_PENALTY: 1.9
EBIKE_PENALTY: 0.7
CAR_PENALTY: 0.7
CP_PENALTY: 1.03
DRT_PENALTY: 1.0
PT_PENALTY: 0.8

# tunning for work/school tours
WORK_PENALTY: 1.0
WORK_PENALTY_ASC_IS_POSITIVE: 0.5

# input tables
#
# activitysim uses "well-known" index and foreign key names for imported tables (e.g. households, persons, land_use)
# as well as for created tables (tours, joint_tour_participants, trips)
# e.g. the households table must have an index column 'household_id' and the foreign key to households in the
# persons table is also household_id. This naming convention allows activitysim to intuit the relationship
# between tables - for instance, to ensure that multiprocess slicing includes all the persons, tours, and trips
# in the same subprocess pipeline. The same strategy is also when chunking choosers, and to support tracing by
# household_id.
#
# the input_table_list index_col directive instructs activitysim to set the imported table index to zone_id
# you cannot change the well-known name of the index by modifying this directive. However, if your input file
# has a different id column name, you can rename it to the required index name with the rename_columns directive.
# In the settings below, the 'TAZ' column in the imported table is renamed 'zone_id' in the rename_columns settings.
#
input_table_list:
  #
  # households (table index 'household_id')
  #
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      HHID: household_id  # household_id is the required index column
      PERSONS: hhsize
      workers: num_workers
      VEHICL: auto_ownership
      TAZ: home_zone_id
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
  #
  # persons (table index 'person_id')
  #
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      PERID: person_id  # person_id is the required index column
    keep_columns:
      - household_id
      - age
      - PNUM
      - sex
      - pemploy
      - pstudent
      - ptype
      - driving_license
      - education
      - roots_person
      - has_car
      - has_bike
      - has_ebike
      - maas_subscription
      - student_pt
      - urbanized
  #
  # land_use (table index 'zone_id')
  #
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    rename_columns:
      TAZ: zone_id  # person_id is the required index column
      COUNTY: county_id
    keep_columns:
      #- DISTRICT
      #- SD
      - county_id
      - TOTHH
      - TOTPOP
      - TOTACRE
      - RESACRE
      - CIACRE
      - TOTEMP
      - AGE0519
      - RETEMPN
      - FPSEMPN
      - HEREMPN
      - OTHEMPN
      - AGREMPN
      - MWTEMPN
      - PRKCST
      - OPRKCST
      - area_type
      - HSENROLL
      - COLLFTE
      - COLLPTE
      - TOPOLOGY
      - TERMINAL
      - ParkingCostHourly
      - FreeParkingCapacity

# convert input CSVs to HDF5 format and save to outputs directory
create_input_store: False

#input_store: ../output/input_data.h5

# number of households to simulate
households_sample_size: 0
# simulate all households
# households_sample_size: 0

# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
# see shadow_pricing.yaml for additional settings
use_shadow_pricing: False

# turn writing of sample_tables on and off for all models
# (if True, tables will be written if DEST_CHOICE_SAMPLE_TABLE_NAME is specified in individual model settings)
want_dest_choice_sample_tables: False

# log interaction simulate/sample expressions that return prohibitive utility values that exclude all alternatives
log_alt_losers: False

# alternate dir to read/write cache (defaults to output_dir)
# used for skim cache, tvpb, and chunk_log caches
#cache_dir: data/cache

##############
#
# chunking
#

# chooser chunk size in gigabytes
# target top memory usage during activitysim run (including shared memory, loaded tables, and transient memory usage)
#chunk_size: 12_000_000_000
chunk_size: 72000000000

# minimum fraction of total chunk_size to reserve for adaptive chunking
min_available_chunk_ratio: 0.05

# initial number of chooser rows for first chunk in training mode
# when there is no pre-existing chunk_cache to set initial value
# ordinarily bigger is better as long as it is not so big it causes memory issues (e.g. accessibility with lots of zones)
default_initial_rows_per_chunk: 5000

# method to calculate memory overhead when chunking is enabled (chunk_size > 0)
chunk_method: hybrid_uss

# chunk training mode
# training to determine the chunking settings written to a cache file that is re-used for production runs
# training
# production
chunk_training_mode: training

# whether to preserve or delete subprocess chunk and mem logs when they are consolidated at end of multiprocess run
keep_chunk_logs: True
keep_mem_logs: True

##############

# - tracing

# trace household id; comment out or leave empty for no trace
# households with all tour types
#  [ 728370 1234067 1402924 1594625 1595333 1747572 1896849 1931818 2222690 2344951 2677154]
trace_hh_id:

# trace origin, destination in accessibility calculation; comment out or leave empty for no trace
# trace_od: [5, 11]
trace_od:

# to resume after last successful checkpoint, specify resume_after: _
#resume_after: trip_destination
resume_after: compute_accessibility

checkpoints: True
# if checkpoints is False, no intermediate checkpoints will be written before the end of run
# (or if multiprocessing, at the end of each multiprocess_step)
#checkpoints: False
# explicit list of models to checkpoint
#checkpoints:
#  - mandatory_tour_scheduling
#  - non_mandatory_tour_scheduling
#  - trip_mode_choice


models:
  - initialize_landuse
  - initialize_households
  - compute_accessibility
  - school_location
  - workplace_location
##  - auto_ownership_simulate
#  - free_parking
#  - cdap_simulate
#  - mandatory_tour_frequency
#  - mandatory_tour_scheduling
##  - joint_tour_frequency
##  - joint_tour_composition
##  - joint_tour_participation
##  - joint_tour_destination
##  - joint_tour_scheduling
#  - non_mandatory_tour_frequency
#  - non_mandatory_tour_destination
#  - non_mandatory_tour_scheduling
#  - tour_mode_choice_simulate
#  - atwork_subtour_frequency
#  - atwork_subtour_destination
#  - atwork_subtour_scheduling
#  - atwork_subtour_mode_choice
#  - stop_frequency
#  - trip_purpose
#  - trip_destination
##  - trip_purpose_and_destination
#  - trip_scheduling
#  - trip_mode_choice
##  - generate_trip_mode_chain_sets
#  - trip_access_egress_mode_choice
##  - trip_access_egress_mode_choice_load
  - write_data_dictionary
  - track_skim_usage
##  - write_trip_matrices
  - write_tables

output_tables:
  h5_store: False
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 3

# - value of time
min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85

household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86
